### ISSUE TITLE
Consider using dotnet-bot for opening release/2.* merge PRs

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#1073]
It knows how to do it, let's use the feature.
Would be cool if it can also assign everyone involved (everyone who has PR unmerged).

The huge advantage is that it would make things visible and harder to forget to merge.

Example: https://github.com/dotnet/sdk/pull/2137

/cc @mkArtakMSFT @natemcmaster  @ryanbrandenburg

**Comment by ryanbrandenburg** [comment]
This is super useful for any time our workflow includes merging a release branch back into dev. The script we use to branch insists (rightly so) on release/2.1 not having any commits that dev doesn't. If we use this method then the person who made the commit, who already has context on this change, will do the merge before it becomes an issue rather than me, with no context, trying to throw it in while we branch.

**Comment by natemcmaster** [comment]
This was done. See https://github.com/dotnet/arcade/pull/483.
