### ISSUE TITLE
Cleanup ANCM installers

### ISSUE THREAD

**Issue by jkotalik** [aspnet/Universe#1496]
- [x] Move all props/targets files to a central location
- [x] Max path issues with nested folders
- [x] Add comments to explain how version variables should be used

**Comment by jkotalik** [comment]
@natemcmaster feel free to add anything I missed.

**Comment by natemcmaster** [comment]
LGTM, thanks.

**Comment by natemcmaster** [comment]
Prior to https://github.com/aspnet/Universe/pull/1456, Version variables always ended in 0.
https://github.com/aspnet/Universe/blob/949c29c59f3ea0a9acb3cbbb0d23a830db99d814/src/Installers/Windows/Wix.props#L4

With https://github.com/aspnet/Universe/pull/1456, we changed this to include a time-based number. 
https://github.com/aspnet/Universe/blob/c37a332a6a220d36ce510569a3a6ab9f13906d17/src/Installers/Windows/Wix.props#L5-L8

@joeloff is this change the right thing to do?

Asking because I know there are funky rules in MSI around file versions, and want to make sure we're doing this right. This variable is used in 4 different ways. Is it okay to re-use for all of them?

1. On `<Product>` elements in .wxs https://github.com/aspnet/Universe/blob/da48de7d7580ce316784dd3e250786ffa7017c25/src/Installers/Windows/SharedFramework/Product.wxs#L3
2. On `<Bundle>` elements in .wxs https://github.com/aspnet/Universe/blob/da48de7d7580ce316784dd3e250786ffa7017c25/src/Installers/Windows/SharedFrameworkBundle/Bundle.wxs#L3
3. As inputs to GUIDs: https://github.com/aspnet/Universe/blob/949c29c59f3ea0a9acb3cbbb0d23a830db99d814/src/Installers/Windows/Wix.targets#L9-L10
4. And now used in ANCM in `<UpgradeVersion`> (`MsiVersion = "1$(Version)"`) https://github.com/aspnet/Universe/blob/c37a332a6a220d36ce510569a3a6ab9f13906d17/src/Installers/Windows/AspNetCoreModule-Setup/Installers/ANCMIISExpressV1/ancm_iis_express.wxs#L75-L78

**Comment by joeloff** [comment]
@natemcmaster For things like ANCM that does upgrades, as long the first 3 parts of the version change, the MSIs should upgrade, e.g. if you release 1.2.3.4 and then ship an MSI with version 1.2.4.4 you should be good. Windows Installer will effectively treat those as 1.2.3.0 and 1.2.4.0 since it ignores the 4th part of the version when considering upgrades.

For bundles, all 4 parts of the version are considered, so 1.2.3.4 will be higher than 1.2.3.3. For things like the shared framework/hosting bundles we've made them be SxS back in 2.1 I believe so this should cause any issues.

**Comment by natemcmaster** [comment]
> For things like the shared framework/hosting bundles we've made them be SxS back in 2.1 I believe so this should cause any issues.

Did you mean "this should **not** cause any issues." ?

**Comment by joeloff** [comment]
Yes, typo. It should have said "shouldn't". Sorry about that

**Comment by natemcmaster** [comment]
Ok, thanks for the info on the versions. @jkotalik sounds like your change is fine.

**Comment by jkotalik** [comment]
I think we may have issues with the current versioning scheme with previous ANCM installers. the installers before used the BUILD_MAJOR as the 3rd number for the msi installation: Ex 2.2.18300.0, rather than the patch version. This would cause msi upgrades to fail. We may need to create a custom ANCMMsiVersion property instead of reusing the version here.

**Comment by jkotalik** [comment]
Doing verification on this now.

**Comment by jkotalik** [comment]
Things look good with a side build for the hosting bundle. Will do a quick pass over after the 2.2 windows installers step is done. Closing for now.
