### ISSUE TITLE
Trigger "build all" when Universe changes...

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#198]
... because changes to the build infrastructure affect everyone. Today, no build on the CI depends on Universe

cc @pranavkm

**Comment by pranavkm** [comment]
We have issues with this since Universe contains files for building `KoreBuild` and for doing release management. Having it kick off a full build when we're doing release build changes (which does happen quite frequently) tends to be quite annoying. Until we separate these two aspects of Universe, I wouldn't want to do this.

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
