### ISSUE TITLE
build.sh will fail on ubuntu when nodejs is not installed

### ISSUE THREAD

**Issue by Romoku** [aspnet/Universe#240]
If nodejs is not installed with an alias `node` then it is downloaded. `signtool.exe` is invoked, but `signtool.exe` does not exist on linux. `/usr/bin/signcode` does exist.

**Comment by Romoku** [comment]
Additionally `bower`, `gulp-cli`, and `copy` npm modules must be installed globally or the `build.sh` will not be able to find them. 

    npm install -g bower gulp-cli copy

**Comment by dougbu** [comment]
This issue remains though the symptoms have changed slightly.
- With many Linux distributions, need both the `nodejs` and the `nodejs-legacy` packages. The second ensures the `node` command that's found in the `$Path` is `nodejs`.
- Scripts no longer attempt to download `node.exe` on Linux machines. This means `node` commands fail as you'd expect, e.g.
```
info: Exec
info:   program: node
info:   commandline: "/home/dougbu/src/Mvc/bin/nodejs/node_modules/bower/bin/bower" install --quiet --config.interactive=false
info:   workingdir: /home/dougbu/src/Mvc/samples/MvcSample.Web
fail: ApplicationName='node', CommandLine='"/home/dougbu/src/Mvc/bin/nodejs/node_modules/bower/bin/bower" install --quiet --config.interactive=false', CurrentDirectory='/home/dougbu/src/Mvc/samples/MvcSample.Web', Native error= Cannot find the specified file
fail: Stack trace:
...
```

Not much can be done here since builds don't run with admin rights.

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
