### ISSUE TITLE
Make Sake accept parameters

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Universe#251]
It's ridiculous that you have to set environment variables in order to configure the build. Environment variables are not discoverable and you have to idea who's using them.

I propose we make the build script accept arguments that you can pass from the command line.

**Comment by dougbu** [comment]
@victorhurdugaci we already have some targets that act like arguments e.g. `--quiet` and `--parallel`. Would it be sufficient to extend that model and leave Sake alone? (Might use environment variables as an implementation detail of course.)

**Comment by victorhurdugaci** [comment]
That will not work. I want to be able to pass the names of the projects to build. There are lots of combinations, too many for hardcoded arguments

**Comment by dougbu** [comment]
Makes sense. The `--X` approach really only works for `bool` command-line arguments (and only if you remember to specify a target like `default` or `verify` :smiley_cat:).

**Comment by dmccaffery** [comment]
I wrote a new, fairly extensible, build system loosely based on KoreBuild (only better, with configurable ... everything through defaults instead of vars) that might prove to be useful. It's currently sitting in VSO, but I plan to release it to GitHub shortly. I'd value any input you might have if you're interested in looking at it before it's released.

**Comment by dmccaffery** [comment]
I wrote a new, fairly extensible, build system loosely based on KoreBuild (only better, with configurable ... everything through defaults instead of vars) that might prove to be useful. It's currently sitting in VSO, but I plan to release it to GitHub shortly. I'd value any input you might have if you're interested in looking at it before it's released.

**Comment by victorhurdugaci** [comment]
Does it support command line parameters? What's the OSS license on it (we cannot look until it has an OSS license)?

**Comment by dmccaffery** [comment]
Unfortunately, no. It's built around Sake, so it has the same limitations. I plan to license it the same as KoreBuild, under MIT 2.0 or whatever it is. Since it uses some ideas from KoreBuild, it needs to have the same license and associated credits (not sure what is required, here, but I definitely want to give credit where it is due). The license file is already committed in VSO. If you ping me an MS account, I'd be happy to add you or whomever to VSO before I add the GitHub remote.

**Comment by dmccaffery** [comment]
Just looked, its Apache 2.0 (same as KoreBuild).

**Comment by dmccaffery** [comment]
As a note, I finally got around to publishing Condo on GitHub: https://github.com/PulseBridge/Condo. I think I came up with a way to handle cmd line arguments, which I will implement soon.

**Comment by victorhurdugaci** [comment]
cc @lodejard @pranavkm

**Comment by Eilon** [comment]
Closing because we are not planning to make changes to this or it is no longer needed.
