### ISSUE TITLE
Enable CI CoreCLR test runs on Linux and OS X 

### ISSUE THREAD

**Issue by muratg** [aspnet/Universe#304]

**Comment by divega** [comment]
@cesarbs please let us know when you are doing this. We want to make sure EF tests are run an work great on Mac.

cc @natemcmaster

**Comment by natemcmaster** [comment]
All EF tests are passing on OSX CI now. This required manually setting locale on our CI agents.

For future reference, due to https://github.com/dotnet/coreclr/issues/2531 I had to manually set environment variables to ensure the thread culture is "en-US", not "en-US-POSIX".

Env variables I added:

Var Name | Value
---------|---------
LANG |	 en_US.UTF-8
LC_COLLATE|	 en_US.UTF-8
LC_CTYPE	| en_US.UTF-8
LC_MESSAGES	| en_US.UTF-8
LC_MONETARY|	 en_US.UTF-8
LC_NUMERIC	| en_US.UTF-8
LC_TIME	| en_US.UTF-8

**Comment by muratg** [comment]
:clap: :100:

**Comment by cesarbs** [comment]
@natemcmaster Did you set them in-proc or globally on the agent?

**Comment by natemcmaster** [comment]
Globally on our Mac agents in `<TeamCity Agent Home>/conf/buildagent.properties`

**Comment by cesarbs** [comment]
This is finally working :smile:

**Comment by natemcmaster** [comment]
Looks like our new agent `aspnetci-a20` is missing these variables.
