### ISSUE TITLE
(Second) Build failing if node is not installed (TeamCity)

### ISSUE THREAD

**Issue by kyubisation** [aspnet/Universe#320]
Hello :-)

If node is not installed (node --version doesn't work), then node is downloaded to the bin directory (_node-install.shade).

However on a TeamCity build (second and following), the target #ci-deep-clean is run, which further down the line runs #clean-bin-folder.
#clean-bin-folder uses the command "rimraf rimrafDir='bin' if='Directory.Exists("bin")'" to delete the bin directory, which to my understanding uses _rimraf.shade which uses the node executable that is located in the bin directory.

This of course results in an error:
[clean-bin-folder] D:\MSBuildAgent\work\Webapp\bin\nodejs\node_modules\rimraf\bin.js:37
[14:33:30][clean-bin-folder]       throw er
[14:33:30][clean-bin-folder]             ^
[14:33:30][clean-bin-folder] Error: EPERM, unlink 'D:\MSBuildAgent\work\Webapp\bin\nodejs\node.exe'

**Comment by dougbu** [comment]
The installation of `node` is intended as a temporary patch for Windows only. The installation is a no-op on all other platforms. Local installation of `node` programs such as `bower` and `grunt-cli` create extremely long paths which can cause failures (e.g. of `dnu restore`) elsewhere in the build. Therefore we install `node` system-wide and `bower`, `grunt-cli`, and `rimraf` globally i.e. with `npm install -g ...` on our CI machines.

More generally are you building aspnet repositories on other CI machines? Our `*.shade` infrastructure isn't really intended for broad use which is why `KoreBuild` packages aren't available in any NuGet.org feed.

**Comment by kyubisation** [comment]
I see. Thanks for the heads-up. :-)
