### ISSUE TITLE
Use `portable-dnxcore50+net45+win8+wp8+wpa81` as TFM to import Newtonsoft.Json instead of portable-net451+win8

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Universe#438]
This reduces the odds of pulling in the wrong imports. Follow up to #430

**Comment by NTaylorMullen** [comment]
Will have to do the same thing for tools that use it too :cry:

**Comment by muratg** [comment]
@pranavkm any change in RC2?

**Comment by pranavkm** [comment]
Yeah, we need to do a pass and bulk update this. It's kinda tricky because some repos require the `portable-net451+win8` to work with some of the Roslyn dependencies.

**Comment by muratg** [comment]
OK, putting this in RC2 to track. Let me know if someone else is going to handle this

**Comment by pranavkm** [comment]
Yeah. I wouldn't mind pawning this off on someone :)

**Comment by muratg** [comment]
@victorhurdugaci could you take this?

**Comment by victorhurdugaci** [comment]
Not sure how much time I'll have for this because I need to do the Antares tests

**Comment by victorhurdugaci** [comment]
Depends on how long it that takes

**Comment by victorhurdugaci** [comment]
I've talked to @moozzyk and @anurse. We don't think this is a bug that we should fix. It would indeed reduce the chances of pulling a wrong TFM but only if Netwonsoft.Json adds new TFMs. Today, it doesn't break because NuGet picks the "closest" match between:

- portable-net40+sl5+wp80+win8+wpa81 
- portable-net45+wp80+win8+wpa81+dnxcore50 

"portable-net451+win8" best matches the second. At most we should add "dnxcreo50" as an import to totally reduce the possible ambiguity but that's just defensive coding for something that might not happen.

This problem will completely go away when Newtonsoft.Json adds support for netstandard.

**Comment by victorhurdugaci** [comment]
I'm going to close this. If I somehow missed something and we actually need this, reopen and comment.
