### ISSUE TITLE
Add a <clear> to every repo's nuget.config

### ISSUE THREAD

**Issue by Eilon** [aspnet/Universe#502]
It will fix issues that people have when they have custom feeds and they clone and build our projects. We've had a few external contributors and members from other teams (and even our own team) run into this.

**Comment by dougbu** [comment]
@Eilon it's pretty easy to undo this per-repo when testing cross-repo changes one at a time. But, that will get old after the 3rd repo. And, what about building Universe with locally-built tools (e.g. BuildTools) in place?

**Comment by pranavkm** [comment]
@dougbu - editing individual NuGet.configs (and not checking them in 😄 ) would still work. I was planning on doing this today whilst I bump up the versions in the dev branch to preview3.

**Comment by dougbu** [comment]
@pranavkm right. Plus, I wasn't aware .deps/build was used as a package source in our Universe builds.

Bottom line, workarounds exist though there's some "and not checking them in" peril.

**Comment by pranavkm** [comment]
Cool. I made the changes as part of my version change today. This can be closed.

**Comment by pranavkm** [comment]
As a follow up to this, I'd like to add `NuGet.config` to the repo's `.gitignore`. This would avoid accidentally checking in changes to the file (when you're doing local cross-repo testing). Any objections to this?

**Comment by Eilon** [comment]
@pranavkm - file a new bug for that? I think that's a good idea but I'd like to get it triaged.

**Comment by smitpatel** [comment]
> A gitignore file specifies intentionally untracked files that Git should ignore. Files already tracked by Git are not affected; see the NOTES below for details.
NOTES
The purpose of gitignore files is to ensure that certain files not tracked by Git remain untracked.
To stop tracking a file that is currently tracked, use git rm --cached.

I don't think .gitignore is the way we could do this.

**Comment by pranavkm** [comment]
@smitpatel - yeah you're right. `git rm --cached` isn't what we want either since we want to track the file, just disallow updates to it (unless done via something like `git add --force`) but there really isn't a git feature for this. Oh well, guess we'll just have to be vigilant about changes to the config file.

**Comment by Eilon** [comment]
I thought this was exactly something you can do with .gitignore? Did anyone try it? I know we discussed doing this "trick" in other places before, but I'm not sure if we ever tried it.

**Comment by pranavkm** [comment]
Seemingly not. Once you force add the file back (`git add --force NuGet.config`), since you do want to commit it to git history, git starts tracking changes to it. There's a `git update-index --assume-unchanged` that's does work correctly, however it's a client-side command and there doesn't seem to be a way to persist it to the server.

**Comment by Eilon** [comment]
Oh well, I guess it's not a super important thing. I think people are pretty good in general at spotting someone changing a nuget.config file.
