### ISSUE TITLE
Check for prerequisites at begining of build

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#517]
We should check for prerequisites like npm and netframework 46 as early in the build as possible and pre-emptivly warn people that they're missing them. This is important because sometimes builds take an hour plus to reach the point where they fail, which can be very frustrating.

**Comment by Eilon** [comment]
Not a high pri issue.

**Comment by natemcmaster** [comment]
This was implemented as a pre-req to building the Razor and UserSecrett VSIX's. Builds of were failing inconsistently because we were picking the wrong versions of Visual Studio, depending on what the machine had installed.

https://github.com/aspnet/BuildTools/pull/448 
https://github.com/aspnet/BuildTools/pull/443
