### ISSUE TITLE
Disable warning xUnit1004: Test methods should not be skipped 

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Universe#518]
At present, the test runner reports skipped test.
Skipped test with skip reason also printed out to console logs
And now xunit also generates warning for skipped test.

If we start treating warning as errors then above can cause failures too.

We should disable xunit warnings globally in universe. How many times do we want to be told about skipped tests anyway.

**Comment by natemcmaster** [comment]
Although there is overlap, xUnit1004 represents a category of test are skipped **permanently** in code. The other category of skipped tests are those skipped dynamically. e.g.
 unmet conditions on a `ConditionalFact/Theory`. xUnit1004 doesn't trigger for those.

We left xUnit1004 enabled as a warning because permanently skipped tests are an actionable item. Remove them or fix them. Tests that never run is a code smell.

**Comment by smitpatel** [comment]
> How many times do we want to be told about skipped tests anyway.

Its not the warning which is issue here, Its reporting same warning 5 times which is utterly useless and does nothing other than growing the build log.

I think this was also discussed with @ryanbrandenburg with EF team in team room once. Warning for flaky test is **code smell** which needs to be fixed. But many times especially for queries, we have written tests (which derives based on model classes), which are complex enough that they don't always work while writing them but we still leave it there. They are tests for features/bugs which are not fixed yet. And xunit warning for them is lovely to have.

Regardless, we disabled this warnings in EF codebase already here https://github.com/aspnet/EntityFramework/pull/8974 so this issue is irrelevant for EF now.
