### ISSUE TITLE
Post-Processing of a release

### ISSUE THREAD

**Issue by smitpatel** [aspnet/Universe#528]
We do process of branching when releasing a version to NuGet.
There is also required post-processing for each release. Steps are below.

1. Every version number has to be pinned instead of floating. We should do this even for test dependencies to make sure build works in future.
2. Change NuGet.Config file to remove all the feeds which can be removed or purged. Once packages are release on NuGet, it should be fetched from NuGet (or aspnetcore-master for non-shipping packages)
3. Creating a release in GitHub (for release notes) causes tag creation. If tag is already created due to this, update the tag with above changes or create a new tag with changes.
4. Once the tag is pushed to GitHub, delete the corresponding rel branch.

We can do above all with a script just like how we branch them. This should be done for v2.0 so that users can create custom builds.

@pranavkm @Eilon

**Comment by Eilon** [comment]
cc @danroth27 because he usually does the GitHub "release" stuff.

**Comment by pranavkm** [comment]
One more step is to publish .Sources packages to the `aspnetcore-master` feed. Since we'd be referencing timestamp free noship packages (`dependencies.props` would say `<AspNetCoreVersion>2.0.0</AspNetCoreVersion>` which includes non-shipping packages, we should produce timestamp free versions of these too.

**Comment by smitpatel** [comment]
@pranavkm - This should be marked as completed right?
