### ISSUE TITLE
Allow having packages in runtime store but not in metapackage

### ISSUE THREAD

**Issue by pakrym** [aspnet/Universe#588]
This is needed only for AI hosting startup in 2.0.x patch
/cc @JunTaoLuo

**Comment by JunTaoLuo** [comment]
To support this we will need
- [ ] Additional column to specify whether the package should be in the runtime store
- [ ] Generate a separate reference project for use when generating the runtime store instead of using the .All metapackage
 - This is an interesting change since it allows us to avoid doing the dance where we build the .All nupkg, use it to generate the store, then shim the new manifests back into the nupkg
- [ ] Reorder the build steps so the metapackage is built after the runtime stores are generated.
