### ISSUE TITLE
Update XUnit to version 2.3.1 due to bug in 2.3.0 that prohibit usage of testrunner inside VS

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Universe#624]
Is there a way that I can override the pinned xunit version? The pinned version is 2.3.0 and that cause runing tests in visual studio throwing the same error as https://github.com/xunit/xunit/issues/1514 and I should like to test with the 2.3.1 version instead to see if that solves the error. Working on an EFCore bug and it is hard to not been able to run and debug test during development. (dotnet test is still working but I lack the debug possibility)

**Comment by smitpatel** [comment]
@Tasteful - You should be able to put version no. in csproj file. KoreBuild raises error for pinned version in csproj but you can manually put that error code for NoWarn.

Something like this
https://github.com/aspnet/EntityFrameworkCore/blob/1030467f778be6ac77ef8b76d8bb927cbd97fc84/src/EFCore/EFCore.csproj#L31-L34

**Comment by Tasteful** [comment]
@smitpatel Thanks, that worked and now I can run the test inside VS again :)

Tested with VS 2017 (15.4.1)

**Comment by yohanmishkin** [comment]
Thanks @smitpatel! Any thoughts on how this might be done in a .Net Framework project?

**Comment by smitpatel** [comment]
@yohanmishkin - Can you elaborate problem you are facing? This issue is something specific to source code of aspnet org

**Comment by yohanmishkin** [comment]
Sure! I believe that `<PackageReference>` is only support in .Net Core, .Net Standard, and UWP projects being developed in VS2017 so I was wondering if there's an easy way to achieve the same ends in a regular .Net Framework (4.5+) project.

**Comment by smitpatel** [comment]
I would recommend reading docs here at https://docs.microsoft.com/en-us/nuget/consume-packages/overview-and-workflow in detail.

I read the note in their docs same as you mentioned, but it is bit misleading.
PackageReference is supported property in new csproj format which is introduced in VS 2017. For older versions, (which we call classical csproj) does not support PackageReference so it requires packages.config file. A new csproj format can also use packages.config if user wishes too.
Above distinction is based on type of project file.

.NET Core, .NET standard, UWP are project type or target frameworks for the project. .NET Framework is also such target. You can create a project which targets .NET Framework in VS 2017 using new csproj format which can use PackageReference. Its just matter of project file format rather than project type.

Based on nuget docs, best place to ask questions about this would be at https://github.com/NuGet/Home

**Comment by yohanmishkin** [comment]
Right on. Thanks!
