### ISSUE TITLE
ApiCheck should check public internal changes in patch branches

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#976]
All of our patch branches should default [this](https://github.com/aspnet/BuildTools/blob/e1c2a4b79748d853196318c6e2e52151846070bd/src/Internal.AspNetCore.Sdk/build/ApiCheck.props#L20) property to false.

**Comment by natemcmaster** [comment]
Note to implementer: try to implement this in one place as possible.

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
