### ISSUE TITLE
ApiCheck Generate should never Exclude Public internals

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Universe#978]
We can run the check with ignore exclude public internals, but we should always generate things with the entire API.

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
